# Generated by Django 4.2.6 on 2023-10-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='gender',
            field=models.BooleanField(default=True, verbose_name='Пол'),
        ),
    ]
