# Generated by Django 4.2.6 on 2023-10-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0002_form_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина'), ('Г', 'Гей'), ('Л', 'Лесбиянка'), ('С', 'Сковородкасексуал')], max_length=1, verbose_name='Пол'),
        ),
    ]
