# Generated by Django 4.2.6 on 2023-10-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0003_form_avatar_alter_form_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='avatar',
            field=models.ImageField(default='https://www.meme-arsenal.com/memes/9deabcb50a53c324b3a4981528215040.jpg', upload_to='', verbose_name='Фото'),
        ),
    ]
