# Generated by Django 4.2.6 on 2023-10-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0004_alter_form_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='searching_for',
            field=models.CharField(choices=[('М', 'Парня'), ('Ж', 'Девушку'), ('В', 'Кого угодно')], default='Всех', max_length=1, verbose_name='Ищу'),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('М', 'Парень'), ('Ж', 'Девушка')], max_length=1, verbose_name='Пол'),
        ),
    ]
