# Generated by Django 4.2.6 on 2023-10-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0006_form_city_form_point_of_searching_alter_form_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('М', 'Парень'), ('Ж', 'Девушка')], default=('М', 'Парень'), max_length=30, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='form',
            name='point_of_searching',
            field=models.CharField(choices=[('О', 'Отношения'), ('С', 'Свидания'), ('Д', 'Дружба'), ('Т', 'Общение')], default=('О', 'Отношения'), max_length=30, verbose_name='Цель знакомства'),
        ),
        migrations.AlterField(
            model_name='form',
            name='searching_for',
            field=models.CharField(choices=[('Парня', 'Парня'), ('Девушку', 'Девушку'), ('Кого угодно', 'Кого угодно')], default=('Девушку', 'Девушку'), max_length=30, verbose_name='Ищу'),
        ),
    ]
