# Generated by Django 4.2.6 on 2023-10-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0008_alter_form_gender_alter_form_point_of_searching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='photos/users', verbose_name='Фото'),
        ),
    ]
