# Generated by Django 4.2.6 on 2023-10-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0009_alter_form_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Profile',
        ),
    ]
