# Generated by Django 4.2.6 on 2023-10-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0010_rename_form_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='searching.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to='searching.profile', verbose_name='Пользователь')),
            ],
            bases=('searching.profile',),
        ),
    ]
