# Generated by Django 4.2.6 on 2023-10-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0011_myprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='searching_for',
        ),
    ]
