# Generated by Django 4.2.6 on 2023-10-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0012_remove_profile_searching_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='photos/users/default_avatar.jpg', upload_to='photos/users', verbose_name='Фото'),
        ),
    ]
