# Generated by Django 4.2.6 on 2023-10-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0015_profile_user_alter_profile_social_delete_myprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
