# Generated by Django 4.2.6 on 2023-10-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0015_profile_owner_delete_myprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='user',
        ),
    ]
