# Generated by Django 4.2.6 on 2023-10-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0019_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_search_high',
            field=models.IntegerField(default=1, verbose_name='Возраст поиска (до)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='age_search_low',
            field=models.IntegerField(default=2, verbose_name='Возраст поиска (от)'),
            preserve_default=False,
        ),
    ]
