# Generated by Django 4.2.6 on 2023-10-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0020_profile_age_search_high_profile_age_search_low'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age_search_high',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age_search_low',
        ),
        migrations.AddField(
            model_name='profile',
            name='age_search_max',
            field=models.IntegerField(default=100, verbose_name='Возраст поиска (до)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='age_search_min',
            field=models.IntegerField(default=0, verbose_name='Возраст поиска (от)'),
        ),
    ]
