# Generated by Django 4.2.6 on 2023-10-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0021_remove_profile_age_search_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_search_min',
            field=models.IntegerField(default=16, verbose_name='Возраст поиска (от)'),
        ),
    ]
