# Generated by Django 4.2.6 on 2023-10-30 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searching', '0022_alter_profile_age_search_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('like_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
            },
        ),
    ]
