# Generated by Django 4.2.6 on 2023-10-30 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searching', '0023_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Reactions',
        ),
    ]
