# Generated by Django 4.2.6 on 2023-10-31 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0025_reactions_like_sender_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='like_sender_profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='like_sender_profile', to='searching.profile', verbose_name='Анкета отправителя'),
        ),
    ]
