# Generated by Django 4.2.6 on 2023-11-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0028_reactions_like_receiver_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=50, verbose_name='Имя1')),
                ('name_2', models.CharField(max_length=50, verbose_name='Имя2')),
                ('avatar_1', models.ImageField(default='photos/default_avatar.jpg', upload_to='photos/users', verbose_name='Фото1')),
                ('avatar_2', models.ImageField(default='photos/default_avatar.jpg', upload_to='photos/users', verbose_name='Фото2')),
                ('social_1', models.CharField(default='@name', max_length=50, verbose_name='Ссылка на соцсеть1')),
                ('social_2', models.CharField(default='@name', max_length=50, verbose_name='Ссылка на соцсеть2')),
            ],
            options={
                'verbose_name': 'Полученная пара',
                'verbose_name_plural': 'Полученные пары',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='photos/default_avatar.jpg', upload_to='photos/users', verbose_name='Фото'),
        ),
    ]
