# Generated by Django 4.2.6 on 2023-11-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0029_newpair_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpair',
            name='avatar_1',
            field=models.ImageField(default='photos/default_avatar.jpg', upload_to='photos/users', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='newpair',
            name='avatar_2',
            field=models.ImageField(default='photos/default_avatar.jpg', upload_to='photos/users', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='newpair',
            name='name_1',
            field=models.CharField(max_length=50, verbose_name='Имя 1'),
        ),
        migrations.AlterField(
            model_name='newpair',
            name='name_2',
            field=models.CharField(max_length=50, verbose_name='Имя 2'),
        ),
        migrations.AlterField(
            model_name='newpair',
            name='social_1',
            field=models.CharField(default='@name', max_length=50, verbose_name='Ссылка на соцсеть 1'),
        ),
        migrations.AlterField(
            model_name='newpair',
            name='social_2',
            field=models.CharField(default='@name', max_length=50, verbose_name='Ссылка на соцсеть 2'),
        ),
    ]
