# Generated by Django 4.2.6 on 2023-11-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0032_remove_newpair_avatar_1_remove_newpair_avatar_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpair',
            name='viewed1',
            field=models.BooleanField(default=False, verbose_name='Просмотрено отправителем'),
        ),
        migrations.AddField(
            model_name='newpair',
            name='viewed2',
            field=models.BooleanField(default=False, verbose_name='Просмотрено получателем'),
        ),
        migrations.AddField(
            model_name='reactions',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
