# Generated by Django 4.2.6 on 2023-11-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0034_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_search_min',
            field=models.IntegerField(default=18, verbose_name='Возраст поиска (от)'),
        ),
    ]
