# Generated by Django 4.2.7 on 2023-11-30 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searching', '0038_alter_profile_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social',
            field=models.CharField(default='@name', max_length=50, verbose_name='Ссылка на соцсеть'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор анкеты'),
        ),
    ]
